### ISSUE TITLE
Math in inline mode in Julia packages

### ISSUE THREAD

**Issue by juliohm** [mitya57/python-markdown-math#13]
Inline mode equations are not rendered in Julia documentation even when I use `\(...\)` as suggested in the docs. Display mode is working just fine with `$$`. Can you please help me debug this issue?

The mkdocs file is [here](https://github.com/juliohm/ImageQuilting.jl/blob/master/docs/mkdocs.yml) and the part of the docs that I am trying to use math notation is the interval [0,1] written [here](https://github.com/juliohm/ImageQuilting.jl/blob/master/docs/src/index.md).

**Comment by mitya57** [comment]
Hi @juliohm!

It works for me if I try to build your package locally and try to use the `\(...\)` in the text. However to achieve that I had to download [`mathjaxhelper.js`](http://juliohm.github.io/ImageQuilting.jl/latest/assets/mathjaxhelper.js) from your site and copy it to my build directory, because it does not seem to be present in the repository.

If you give me more details about what you are doing to build the docs, I would try to look at this again.

Also, the `tex2jax` extension conflicts with what python-markdown-math is doing. Please remove the first `MathJax.Hub.Config` call from `mathjaxhelper.js`, and also drop the `?config=TeX-AMS_HTML` part of the MathJax URL.

**Comment by juliohm** [comment]
Hi @mitya57, thank you for your help. I am using the official package for documentation in Julia: https://github.com/JuliaDocs/Documenter.jl Followed their instructions to get this right.

Could you please give advice in this scenario with Documenter.jl? Every time I push to GitHub I get automatic documentation builds.

**Comment by mitya57** [comment]
I installed Julia and the needed packages, and ran `julia make.jl` and then `mkdocs build`. The `\([0,1]\)` expression still renders correctly, though it takes a pair of seconds before the equation is really rendered.

If it fails for you, can you please generate the documentation and share it with me? Either the whole build as archive, or at least just `index.html`.

**Comment by juliohm** [comment]
Thank you @mitya57, the archive is attached with all the files under the build directory: [build.zip](https://github.com/mitya57/python-markdown-math/files/655657/build.zip)

**Comment by mitya57** [comment]
Oh, I see what is the issue now. It looks like Documenter.jl “eats” the math delimiters. In your `src/index.md`, you have `\([0,1]\)`, but in the generated `build/index.md` it turns into `([0,1])` without the backslashes.

This happens before python-markdown-math even has a chance to process it, so this is not a my bug, but rather a bug in Documenter.jl. I have reported it as JuliaDocs/Documenter.jl#377.

As a workaround, you can use double backslashes, like `\\([0,1]\\)`.

**Comment by juliohm** [comment]
Thank you very much @mitya57, really helpful. Have a great day.
